### ISSUE TITLE
Piwigo 12.1.0 error

### ISSUE THREAD

**Issue by max-ima** [Piwigo/Password_Policy#2]
Settings/Management/ click on Profile:

Fatal error: Uncaught --> Smarty: Unable to load template 'file:profile.tpl' <-- thrown in C:\AppServ\www\avs\include\smarty\libs\sysplugins\smarty_internal_template.php on line 195

**Comment by LintyDev** [comment]
Done with 791517f4282a93802bd5355f9e5d63dbdfe1d4cf
